<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-807JA60V" ignored="4" name="TestRunner-2" tests="17" failures="2" timestamp="2022-01-21T15:34:57 IST" time="101.548" errors="0">
  <testcase name="configBS" time="0.004" classname="com.crm.GenericLibrary.BaseClass"/>
  <testcase name="createOrgTest" time="14.395" classname="com.crm.comcas.orgTest.CreateOrganization"/>
  <testcase name="createOrgWithIndutriesTest" time="14.433" classname="com.crm.comcas.orgTest.CreateOrganization"/>
  <testcase name="bookTicket" time="0.0" classname="practice.BookTicket"/>
  <testcase name="bookTicket" time="0.0" classname="practice.BookTicket"/>
  <testcase name="bookTicket" time="0.0" classname="practice.BookTicket"/>
  <testcase name="bookTicket" time="0.002" classname="practice.BookTicket"/>
  <testcase name="bookTicket" time="0.001" classname="practice.BookTicket"/>
  <testcase name="configBS" time="0.001" classname="com.crm.GenericLibrary.BaseClass"/>
  <testcase name="configBS" time="0.001" classname="com.crm.GenericLibrary.BaseClass"/>
  <testcase name="CreateContactWithOrgTest" time="0.046" classname="com.crm.comcast.contacttest.CreateOrganization">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.crm.GenericLibrary.ExcelUtility.getDataFromExcel(ExcelUtility.java:26)
at com.crm.comcast.contacttest.CreateOrganization.CreateContactWithOrgTest(CreateOrganization.java:24)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- CreateContactWithOrgTest -->
  <testcase name="bookTicket" time="0.001" classname="practice.SampleTest_dataProvider"/>
  <testcase name="bookTicket" time="0.002" classname="practice.SampleTest_dataProvider"/>
  <testcase name="bookTicket" time="0.0" classname="practice.SampleTest_dataProvider"/>
  <testcase name="bookTicket" time="0.002" classname="practice.SampleTest_dataProvider"/>
  <testcase name="bookTicket" time="0.003" classname="practice.SampleTest_dataProvider"/>
  <testcase name="UnitTest" time="0.036" classname="practice.ProjectUnitTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at practice.ProjectUnitTest.UnitTest(ProjectUnitTest.java:39)
at java.util.ArrayList.forEach(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- UnitTest -->
  <testcase name="@BeforeSuite configBS" time="0.0" classname="com.crm.GenericLibrary.BaseClass">
    <ignored/>
  </testcase> <!-- @BeforeSuite configBS -->
  <testcase name="@BeforeSuite configBS" time="0.0" classname="com.crm.GenericLibrary.BaseClass">
    <ignored/>
  </testcase> <!-- @BeforeSuite configBS -->
  <testcase name="@AfterSuite configAS" time="0.0" classname="com.crm.GenericLibrary.BaseClass">
    <ignored/>
  </testcase> <!-- @AfterSuite configAS -->
  <testcase name="@AfterSuite configAS" time="0.0" classname="com.crm.GenericLibrary.BaseClass">
    <ignored/>
  </testcase> <!-- @AfterSuite configAS -->
</testsuite> <!-- TestRunner-2 -->
